// 일정/곡 단일 소스(single source of truth).
// 브라우저(app.js)와 SQL 생성 스크립트(scripts/build-schedule-sql.mjs)가 함께 import한다.
// 일정/곡을 바꿀 때는 이 파일만 수정하고 `npm run schedule:sql`로 마이그레이션을 재생성한다.

const defaultTracks = [
  {
    number: "01",
    title: "Psyche",
    due: "2026-06-25",
    eventId: "demo-psyche",
    document: "tracks/01_psyche/README.md",
    lyrics: "lyrics/01_Psyche.txt",
  },
  {
    number: "02",
    title: "괜한 말",
    due: "2026-06-28",
    eventId: "demo-gwaenhan-mal",
    document: "tracks/02_gwaenhan-mal/README.md",
    lyrics: "lyrics/02_괜한_말.txt",
  },
  {
    number: "03",
    title: "날 좀 봐줘요, 좀 봐줘요",
    due: "2026-07-01",
    eventId: "demo-look-at-me",
    document: "tracks/03_look-at-me/README.md",
    lyrics: "lyrics/03_날_좀_봐줘요_좀_봐줘요.txt",
  },
  {
    number: "04",
    title: "누군가의",
    due: "2026-07-03",
    eventId: "demo-nugungaui",
    document: "tracks/04_nugungaui/README.md",
    lyrics: "lyrics/04_누군가의.txt",
  },
  {
    number: "05",
    title: "대동제",
    due: "2026-07-05",
    eventId: "demo-daedongje",
    document: "tracks/05_daedongje/README.md",
    lyrics: "lyrics/05_대동제.txt",
  },
  {
    number: "06",
    title: "또다시",
    due: "2026-07-09",
    eventId: "demo-ttodasi",
    document: "tracks/06_ttodasi/README.md",
    lyrics: "lyrics/06_또다시.txt",
  },
  {
    number: "07",
    title: "새벽 두 시",
    due: "2026-07-12",
    eventId: "demo-2am",
    document: "tracks/07_2am/README.md",
    lyrics: "lyrics/07_새벽_두_시.txt",
  },
  {
    number: "08",
    title: "소란스러운 밤",
    due: "2026-07-16",
    eventId: "demo-noisy-night",
    document: "tracks/08_noisy-night/README.md",
    lyrics: "lyrics/08_소란스러운_밤.txt",
  },
  {
    number: "09",
    title: "스물 여덟",
    due: "2026-07-19",
    eventId: "demo-twenty-eight",
    document: "tracks/09_twenty-eight/README.md",
    lyrics: "lyrics/09_스물_여덟.txt",
  },
  {
    number: "10",
    title: "good night",
    due: "2026-06-21",
    eventId: "demo-good-night",
    document: "tracks/10_good-night/README.md",
    lyrics: "lyrics/10_good_night.txt",
  },
  {
    number: "11",
    title: "부둣가",
    due: "2026-07-20",
    eventId: "demo-budutga",
    document: "tracks/11_budutga/README.md",
    lyrics: "lyrics/11_부둣가.txt",
  },
];

const demoDetail =
  "통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.";
const demoResult = "전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모";

const defaultEvents = [
  {
    id: "demo-template",
    date: "2026-06-18",
    end: "2026-06-20",
    title: "데모 녹음 템플릿 준비",
    phase: "demo",
    duration: "60분",
    result: "입력 레벨, 파일명, 기본 트랙과 저장 경로 확정",
    detail: "첫 녹음 전에 반복해서 사용할 최소한의 세션 템플릿을 만든다. 소리 선택이나 플러그인 비교는 하지 않는다.",
    document: "docs/DEMO_PLAN.md",
  },
  {
    id: "demo-good-night",
    date: "2026-06-21",
    title: "good night 데모",
    phase: "demo",
    duration: "60분",
    result: demoResult,
    detail: demoDetail,
    track: "good night",
    document: "tracks/10_good-night/README.md",
    lyrics: "lyrics/10_good_night.txt",
    milestone: true,
  },
  {
    id: "demo-good-night-arrangement-sketch",
    date: "2026-06-22",
    title: "good night 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "추가 악기 후보 1~2개와 다음 실험 조합 1개",
    detail:
      "기타+보컬 데모를 바로 다시 들으며 어떤 악기가 붙어도 중심이 흐려지지 않는지 확인한다. 편곡 확정이 아니라 다음 실험 출발점만 남긴다.",
    track: "good night",
    document: "tracks/10_good-night/README.md",
    lyrics: "lyrics/10_good_night.txt",
  },
  {
    id: "demo-psyche",
    date: "2026-06-25",
    title: "Psyche 데모",
    phase: "demo",
    duration: "60~90분",
    result: demoResult,
    detail: demoDetail,
    track: "Psyche",
    document: "tracks/01_psyche/README.md",
    lyrics: "lyrics/01_Psyche.txt",
  },
  {
    id: "demo-psyche-arrangement-sketch",
    date: "2026-06-26",
    title: "Psyche 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "추가 악기 후보 2개와 첫 조합 메모",
    detail:
      "기타+보컬 데모를 들으며 곡의 중심을 해치지 않는 추가 악기 후보를 적는다. 가장 먼저 시험할 조합 하나만 남긴다.",
    track: "Psyche",
    document: "tracks/01_psyche/README.md",
    lyrics: "lyrics/01_Psyche.txt",
  },
  {
    id: "demo-gwaenhan-mal",
    date: "2026-06-28",
    title: "괜한 말 데모",
    phase: "demo",
    duration: "60분",
    result: demoResult,
    detail: demoDetail,
    track: "괜한 말",
    document: "tracks/02_gwaenhan-mal/README.md",
    lyrics: "lyrics/02_괜한_말.txt",
  },
  {
    id: "demo-gwaenhan-mal-arrangement-sketch",
    date: "2026-06-29",
    title: "괜한 말 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "추가 악기 후보 2개와 첫 조합 메모",
    detail:
      "데모를 바로 들으며 악기 수를 늘릴지, 질감만 보탤지 판단해본다. 다음 편곡 실험에 바로 옮길 조합 하나를 남긴다.",
    track: "괜한 말",
    document: "tracks/02_gwaenhan-mal/README.md",
    lyrics: "lyrics/02_괜한_말.txt",
  },
  {
    id: "demo-look-at-me",
    date: "2026-07-01",
    title: "날 좀 봐줘요, 좀 봐줘요 데모",
    phase: "demo",
    duration: "60분",
    result: demoResult,
    detail: demoDetail,
    track: "날 좀 봐줘요, 좀 봐줘요",
    document: "tracks/03_look-at-me/README.md",
    lyrics: "lyrics/03_날_좀_봐줘요_좀_봐줘요.txt",
  },
  {
    id: "demo-look-at-me-arrangement-sketch",
    date: "2026-07-02",
    title: "날 좀 봐줘요, 좀 봐줘요 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "후렴 질감 메모와 첫 악기 조합 1개",
    detail:
      "후렴의 에너지를 유지하면서 어떤 질감이 더 붙을 수 있는지 짧게 정리한다. 보컬과 통기타의 중심은 건드리지 않는다.",
    track: "날 좀 봐줘요, 좀 봐줘요",
    document: "tracks/03_look-at-me/README.md",
    lyrics: "lyrics/03_날_좀_봐줘요_좀_봐줘요.txt",
  },
  {
    id: "demo-nugungaui",
    date: "2026-07-03",
    title: "누군가의 데모",
    phase: "demo",
    duration: "60~90분",
    result: demoResult,
    detail: demoDetail,
    track: "누군가의",
    document: "tracks/04_nugungaui/README.md",
    lyrics: "lyrics/04_누군가의.txt",
  },
  {
    id: "demo-daedongje",
    date: "2026-07-05",
    title: "대동제 데모",
    phase: "demo",
    duration: "60~90분",
    result: "리듬 강세 정리, 보컬/기타 재녹음, 후반 일렉 솔로 테스트 메모",
    detail:
      "드럼과 베이스의 박자, 강세를 먼저 정리하고 보컬과 기타를 다시 녹음한다. 데모 후반에는 뒷부분 일렉 솔로가 어울리는지도 가볍게 시험한다.",
    track: "대동제",
    document: "tracks/05_daedongje/README.md",
    lyrics: "lyrics/05_대동제.txt",
  },
  {
    id: "demo-ttodasi",
    date: "2026-07-09",
    title: "또다시 데모",
    phase: "demo",
    duration: "60분",
    result: demoResult,
    detail: demoDetail,
    track: "또다시",
    document: "tracks/06_ttodasi/README.md",
    lyrics: "lyrics/06_또다시.txt",
  },
  {
    id: "demo-nugungaui-arrangement-sketch",
    date: "2026-07-04",
    title: "누군가의 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "추가 악기 후보 2~3개와 첫 조합 1개",
    detail:
      "기타+보컬 데모를 다시 들으며 다른 악기 구성을 상상해본다. 편곡 확정이 아니라 다음 편곡 실험에서 가장 먼저 만져볼 조합 하나를 남기는 데 집중한다.",
    track: "누군가의",
    document: "tracks/04_nugungaui/README.md",
    lyrics: "lyrics/04_누군가의.txt",
  },
  {
    id: "demo-daedongje-arrangement-sketch",
    date: "2026-07-06",
    title: "대동제 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "드럼/베이스 강세 기반 추가 악기 조합 1안",
    detail:
      "이미 잡힌 리듬 강세를 기준으로 어떤 악기를 더하면 힘이 살아나는지 짧게 비교한다. 후반 일렉 솔로는 유지하되, 다른 악기와 겹치지 않는 한 가지 조합만 남긴다.",
    track: "대동제",
    document: "tracks/05_daedongje/README.md",
    lyrics: "lyrics/05_대동제.txt",
  },
  {
    id: "demo-ttodasi-arrangement-sketch",
    date: "2026-07-10",
    title: "또다시 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "제출용 톤을 해치지 않는 추가 악기 조합 1안",
    detail:
      "공모전 제출용 데모의 중심을 해치지 않는 범위에서만 다른 악기를 상상해본다. 보컬과 통기타를 흐리지 않는 조합 하나를 정리해 다음 편곡 출발점으로 남긴다.",
    track: "또다시",
    document: "tracks/06_ttodasi/README.md",
    lyrics: "lyrics/06_또다시.txt",
  },
  {
    id: "demo-2am",
    date: "2026-07-12",
    title: "새벽 두 시 데모",
    phase: "demo",
    duration: "60~90분",
    result: "전체 1테이크, 대체 가사 판단과 질감 스케치 메모",
    detail: demoDetail,
    track: "새벽 두 시",
    document: "tracks/07_2am/README.md",
    lyrics: "lyrics/07_새벽_두_시.txt",
  },
  {
    id: "demo-2am-arrangement-sketch",
    date: "2026-07-13",
    title: "새벽 두 시 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "대체 질감 메모와 첫 악기 조합 1개",
    detail:
      "데모에서 느껴진 빈 공간을 기준으로 어떤 질감이 어울리는지 정리한다. 다음 편곡 실험에서 바로 비교할 조합 하나를 남긴다.",
    track: "새벽 두 시",
    document: "tracks/07_2am/README.md",
    lyrics: "lyrics/07_새벽_두_시.txt",
  },
  {
    id: "demo-noisy-night",
    date: "2026-07-16",
    title: "소란스러운 밤 데모",
    phase: "demo",
    duration: "60~90분",
    result: demoResult,
    detail: demoDetail,
    track: "소란스러운 밤",
    document: "tracks/08_noisy-night/README.md",
    lyrics: "lyrics/08_소란스러운_밤.txt",
  },
  {
    id: "demo-noisy-night-arrangement-sketch",
    date: "2026-07-17",
    title: "소란스러운 밤 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "추가 악기 스케치와 첫 조합 1개",
    detail:
      "기타+보컬 데모를 들으며 곡의 소란스러움을 키울지, 반대로 여백을 살릴지 가닥을 잡아본다. 다음 실험 조합 하나만 정리한다.",
    track: "소란스러운 밤",
    document: "tracks/08_noisy-night/README.md",
    lyrics: "lyrics/08_소란스러운_밤.txt",
  },
  {
    id: "demo-twenty-eight",
    date: "2026-07-19",
    title: "스물 여덟 데모",
    phase: "demo",
    duration: "60분",
    result: demoResult,
    detail: demoDetail,
    track: "스물 여덟",
    document: "tracks/09_twenty-eight/README.md",
    lyrics: "lyrics/09_스물_여덟.txt",
    milestone: true,
  },
  {
    id: "demo-twenty-eight-arrangement-sketch",
    date: "2026-07-20",
    title: "스물 여덟 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "다음 편곡 출발 악기 조합 메모",
    detail:
      "데모를 다시 들으며 곡의 온도를 유지하는 악기 조합을 상상해본다. 가장 먼저 손댈 조합 하나만 남긴다.",
    track: "스물 여덟",
    document: "tracks/09_twenty-eight/README.md",
    lyrics: "lyrics/09_스물_여덟.txt",
  },
  {
    id: "demo-budutga",
    date: "2026-07-20",
    title: "부둣가 데모",
    phase: "demo",
    duration: "60~90분",
    result: demoResult,
    detail: demoDetail,
    track: "부둣가",
    document: "tracks/11_budutga/README.md",
    lyrics: "lyrics/11_부둣가.txt",
  },
  {
    id: "demo-budutga-arrangement-sketch",
    date: "2026-07-21",
    title: "부둣가 데모 리뷰 + 악기 아이디어 정리",
    phase: "demo",
    duration: "30분",
    result: "후렴 기준 악기 조합 메모",
    detail:
      "데모를 다시 들으며 후렴의 중심을 기준으로 어떤 악기가 자연스럽게 들어올 수 있는지 정리한다. 다음 편곡 실험의 첫 조합 하나를 남긴다.",
    track: "부둣가",
    document: "tracks/11_budutga/README.md",
    lyrics: "lyrics/11_부둣가.txt",
  },
  {
    id: "demo-buffer",
    date: "2026-07-21",
    title: "전곡 데모 보충 및 마감",
    phase: "demo",
    duration: "최대 2시간",
    result: "후보 11곡 모두 판단 가능한 파일 보유",
    detail: "누락 파일과 판단이 불가능한 테이크만 보충한다. 새 아이디어나 음색 탐색은 다음 단계로 넘긴다.",
    document: "docs/DEMO_PLAN.md",
    milestone: true,
  },
  {
    id: "structure-listen",
    date: "2026-07-22",
    end: "2026-07-24",
    title: "11곡 연속 청취와 비교",
    phase: "structure",
    duration: "2회 × 90분",
    result: "각 곡의 키, 템포, 구조 문제 목록",
    detail: "녹음 직후의 감각이 아닌 앨범 전체 흐름으로 판단한다. 곡마다 바꿀 것 한 가지와 유지할 것 한 가지를 적는다.",
    document: "docs/DEMO_PLAN.md",
  },
  {
    id: "structure-retest",
    date: "2026-07-25",
    end: "2026-07-28",
    title: "키·BPM 재테스트",
    phase: "structure",
    duration: "최대 4곡",
    result: "판단이 어려운 곡의 후보 키/BPM 비교 파일",
    detail: "모든 곡을 다시 녹음하지 않는다. 최고음, 최저음 또는 그루브가 불분명한 최대 네 곡만 짧게 비교한다.",
    document: "docs/DEMO_PLAN.md",
  },
  {
    id: "structure-lock",
    date: "2026-07-29",
    end: "2026-07-31",
    title: "키·BPM·구조 확정",
    phase: "structure",
    duration: "3시간",
    result: "최종 후보 8~9곡과 곡별 기본 정보 확정",
    detail: "편곡 테스트가 시작된 뒤 반복해서 되돌아가지 않도록 곡의 뼈대를 결정 기록에 남긴다.",
    document: "docs/DECISIONS.md",
    milestone: true,
  },
  {
    id: "post-demo-direction",
    date: "2026-07-29",
    end: "2026-08-01",
    title: "데모 이후 방향 논의",
    phase: "structure",
    duration: "2회 × 60분",
    result: "최종 후보, 곡별 편곡 출발점, 모니터 스피커 준비 계획",
    detail:
      "데모에서 간단한 편곡까지 한번 얹어본 상태를 기준으로, 어떤 곡을 밀고 어떤 곡을 줄일지 정리한다. 이때 편곡 시작 전 필요한 모니터 스피커 구매와 배치 일정도 함께 잠근다.",
    document: "docs/POST_DEMO_DIRECTION.md",
  },
  {
    id: "arrangement-monitoring",
    date: "2026-08-01",
    end: "2026-08-03",
    title: "모니터 스피커 구매·배치",
    phase: "arrangement",
    duration: "최대 3일",
    result: "편곡 판단용 모니터링 환경 준비",
    detail:
      "데모 단계와 달리 편곡 판단은 스피커 기준으로 진행한다. 구매, 배치, 기준 청취까지 끝내고 나서 곡별 편곡 실험에 들어간다.",
    document: "docs/POST_DEMO_DIRECTION.md",
  },
  {
    id: "arrangement-palette",
    date: "2026-08-03",
    end: "2026-08-04",
    title: "앨범 사운드 팔레트 설정",
    phase: "arrangement",
    duration: "2시간",
    result: "통기타·보컬의 공통 질감과 추가 악기 원칙",
    detail: "모니터 스피커 셋업 이후, 곡마다 별개의 세계를 만들기 전에 앨범 전체에 반복될 공간감, 악기 수와 보컬 거리감을 정한다.",
    document: "docs/ALBUM.md",
  },
  {
    id: "arrangement-week-1",
    rail: true,
    date: "2026-08-05",
    end: "2026-08-10",
    title: "편곡 테스트 1주차",
    phase: "arrangement",
    duration: "3곡",
    result: "3곡의 편곡안 A/B와 선택 메모",
    detail: "중요도가 높은 곡 세 곡부터 추가 악기, 리듬과 공간감의 두 가지 안을 빠르게 비교한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "arrangement-week-2",
    rail: true,
    date: "2026-08-11",
    end: "2026-08-16",
    title: "편곡 테스트 2주차",
    phase: "arrangement",
    duration: "3곡",
    result: "다음 3곡의 편곡 방향 확정",
    detail: "첫 주에 정한 앨범 팔레트를 적용하되 곡별 역할이 겹치지 않는지 확인한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "arrangement-week-3",
    rail: true,
    date: "2026-08-17",
    end: "2026-08-22",
    title: "편곡 테스트 3주차",
    phase: "arrangement",
    duration: "남은 2~3곡",
    result: "전곡 편곡 방향과 본녹음 순서",
    detail: "남은 곡을 정리하고 본녹음에 필요한 악기, 연주자와 세션 순서를 확정한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "arrangement-lock",
    date: "2026-08-23",
    title: "전곡 편곡 방향 마감",
    phase: "arrangement",
    duration: "마감",
    result: "본녹음에 들어갈 최종 편곡안",
    detail: "이후에는 연주의 완성도와 소리의 품질에 집중한다. 새로운 편곡 방향은 추가하지 않는다.",
    document: "docs/DECISIONS.md",
    milestone: true,
  },
  {
    id: "recording-batch-a",
    rail: true,
    date: "2026-08-24",
    end: "2026-08-30",
    title: "본녹음 묶음 A",
    phase: "recording",
    duration: "2곡",
    result: "최종 통기타·메인 보컬 2곡",
    detail: "편곡 확신이 가장 높은 두 곡부터 최종 통기타와 메인 보컬을 녹음한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "recording-batch-b",
    rail: true,
    date: "2026-08-31",
    end: "2026-09-06",
    title: "본녹음 묶음 B",
    phase: "recording",
    duration: "2곡",
    result: "최종 통기타·메인 보컬 누적 4곡",
    detail: "메인 테이크를 우선 확정하고 더블링과 코러스는 별도 세션으로 분리한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "recording-batch-c",
    rail: true,
    date: "2026-09-07",
    end: "2026-09-13",
    title: "본녹음 묶음 C",
    phase: "recording",
    duration: "2곡 + 크레딧 초안",
    result: "최종 녹음 누적 6곡, 참여자 크레딧 목록",
    detail: "두 곡을 녹음하면서 지금까지 참여한 연주자, 엔지니어와 사용 악기를 함께 기록한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "recording-batch-d",
    rail: true,
    date: "2026-09-14",
    end: "2026-09-19",
    title: "본녹음 묶음 D",
    phase: "recording",
    duration: "남은 2~3곡",
    result: "전곡 최종 통기타·메인 보컬",
    detail: "남은 곡과 필수 코러스, 더블링을 마친다. 선택적 장식 파트는 우선순위를 낮춘다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "recording-lock",
    date: "2026-09-20",
    title: "본녹음 핵심 마감",
    phase: "recording",
    duration: "마감",
    result: "전곡 최종 통기타·메인 보컬 확보",
    detail: "이 날짜 이후 본녹음은 누락과 명백한 문제를 해결하는 보충 녹음으로만 제한한다.",
    document: "docs/SCHEDULE.md",
    milestone: true,
  },
  {
    id: "post-edit-week",
    date: "2026-09-21",
    end: "2026-09-27",
    title: "보충 녹음·컴핑·편집",
    phase: "post",
    duration: "1주",
    result: "베스트 테이크, 튠과 타이밍 정리",
    detail: "재녹음 목록을 먼저 닫고 컴핑, 호흡, 노이즈와 타이밍을 정리한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "post-recording-close",
    date: "2026-09-28",
    end: "2026-09-30",
    title: "녹음 완전 마감·믹스 준비",
    phase: "post",
    duration: "3일",
    result: "정리된 세션, 트랙명, 믹스 전달 파일",
    detail: "사용하지 않는 트랙을 숨기고 파일명, 시작점, 샘플레이트와 레퍼런스 바운스를 확인한다.",
    document: "docs/SCHEDULE.md",
    milestone: true,
  },
  {
    id: "post-mix-prep",
    date: "2026-10-01",
    end: "2026-10-04",
    title: "믹스 기준 설정",
    phase: "post",
    duration: "4일",
    result: "기준곡 1곡과 앨범 믹스 원칙",
    detail: "보컬의 전면감, 통기타 크기와 저역 기준을 한 곡에서 먼저 확정한다.",
    document: "docs/SCHEDULE.md",
  },
  {
    id: "post-mix-a",
    rail: true,
    date: "2026-10-05",
    end: "2026-10-11",
    title: "1차 믹스 전반부",
    phase: "post",
    duration: "4곡",
    result: "전반부 곡 1차 믹스",
    detail: "개별 곡의 화려함보다 기준곡과의 보컬·통기타 크기 일관성을 확인한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "post-mix-b",
    rail: true,
    date: "2026-10-12",
    end: "2026-10-18",
    title: "1차 믹스 후반부",
    phase: "post",
    duration: "남은 4~5곡",
    result: "전곡 1차 믹스와 연속 청취본",
    detail: "전곡을 순서대로 들으며 음량, 공간감과 곡 사이의 전환을 기록한다.",
    document: "docs/TRACK_STATUS.md",
  },
  {
    id: "post-mix-revision-1",
    date: "2026-10-19",
    end: "2026-10-25",
    title: "믹스 수정 1차·가사/크레딧 교정",
    phase: "post",
    duration: "1주",
    result: "수정 믹스와 확정 가사·크레딧",
    detail: "믹스 수정은 곡마다 핵심 세 가지 이내로 제한한다. 동시에 제출용 가사와 크레딧을 교정한다.",
    document: "docs/ALBUM.md",
  },
  {
    id: "post-mix-final",
    date: "2026-10-26",
    end: "2026-10-30",
    title: "최종 믹스 마감",
    phase: "post",
    duration: "5일",
    result: "마스터링용 전곡 최종 믹스",
    detail: "음악적 아이디어 추가를 중단하고 클릭, 노이즈, 출력 형식과 곡 시작·끝을 검수한다.",
    document: "docs/SCHEDULE.md",
    milestone: true,
  },
  {
    id: "post-master",
    date: "2026-10-31",
    end: "2026-11-06",
    title: "마스터링·트랙 순서 확정",
    phase: "post",
    duration: "1주",
    result: "전곡 마스터와 최종 트랙 순서",
    detail: "다양한 재생 환경에서 확인하고 트랙 간 음량, 질감과 여백을 확정한다.",
    document: "docs/SCHEDULE.md",
    milestone: true,
  },
  {
    id: "delivery-package",
    date: "2026-11-07",
    end: "2026-11-09",
    title: "유통 제출 패키지 조립",
    phase: "delivery",
    duration: "3일",
    result: "마스터, 커버, 가사, 크레딧, 메타데이터",
    detail: "곡 제목 표기, 참여자 이름, 작사·작곡·편곡 정보와 파일명을 하나의 제출본으로 모은다.",
    document: "docs/ALBUM.md",
  },
  {
    id: "delivery-qa",
    date: "2026-11-10",
    end: "2026-11-12",
    title: "제출 전 최종 검수",
    phase: "delivery",
    duration: "3일",
    result: "오탈자와 파일 오류가 없는 최종 패키지",
    detail: "처음부터 다시 입력하지 말고 체크리스트에 따라 파일과 메타데이터를 대조한다.",
    document: "docs/SCHEDULE.md",
  },
  {
    id: "delivery-submit",
    date: "2026-11-13",
    title: "유통사 전달",
    phase: "delivery",
    duration: "고정 마감",
    result: "앨범 발매 자료 제출 완료",
    detail: "12월 4일 발매를 위해 움직일 수 없는 최종 제출일이다.",
    document: "docs/SCHEDULE.md",
    milestone: true,
  },
  {
    id: "release-distribution-check",
    date: "2026-11-16",
    end: "2026-11-22",
    title: "유통 반영 확인·발매 콘텐츠 준비",
    phase: "release",
    duration: "1주",
    result: "플랫폼 정보 확인과 발매 공지 자료",
    detail: "유통사에서 전달되는 미리보기와 표기를 확인하고 발매 공지에 필요한 이미지와 문구를 확정한다.",
    document: "docs/SCHEDULE.md",
  },
  {
    id: "release-promo-week",
    date: "2026-11-23",
    end: "2026-11-29",
    title: "발매 전 공개 일정 실행",
    phase: "release",
    duration: "1주",
    result: "티저와 발매 안내 공개",
    detail: "준비된 콘텐츠를 일정대로 공개하고 음악 파일 자체는 다시 수정하지 않는다.",
    document: "docs/SCHEDULE.md",
  },
  {
    id: "release-final-week",
    date: "2026-11-30",
    end: "2026-12-03",
    title: "발매 주 최종 확인",
    phase: "release",
    duration: "4일",
    result: "링크, 소개문, 크레딧과 당일 게시물 준비",
    detail: "발매 당일 필요한 링크와 게시물을 준비하고 휴식 시간을 확보한다.",
    document: "docs/SCHEDULE.md",
  },
  {
    id: "release-day",
    date: "2026-12-04",
    title: "정규 앨범 발매",
    phase: "release",
    duration: "발매일",
    result: "앨범 공개와 플랫폼 재생 확인",
    detail: "플랫폼별 앨범 표기와 재생 상태를 확인하고 발매 공지를 게시한다.",
    document: "docs/ALBUM.md",
    milestone: true,
  },
];

// 기본(오프라인 폴백) 데이터에도 배열 작성 순서를 sort_order로 부여해,
// Supabase 데이터와 동일한 정렬 규칙(날짜 → sort_order)을 따르게 한다.
defaultEvents.forEach((event, index) => {
  if (event.sortOrder === undefined || event.sortOrder === null) {
    event.sortOrder = (index + 1) * 10;
  }
});
defaultTracks.forEach((track, index) => {
  if (track.sortOrder === undefined || track.sortOrder === null) {
    track.sortOrder = (index + 1) * 10;
  }
});

export { defaultTracks, demoDetail, demoResult, defaultEvents };
