delete from public.album_tracks;
delete from public.album_events;

insert into public.album_events (
  id, sort_order, date, "end", title, phase, duration, result, detail, track, document, lyrics, milestone
)
values
  ('demo-template', 10, '2026-06-18', '2026-06-20', '데모 녹음 템플릿 준비', 'demo', '60분', '입력 레벨, 파일명, 기본 트랙과 저장 경로 확정', '첫 녹음 전에 반복해서 사용할 최소한의 세션 템플릿을 만든다. 소리 선택이나 플러그인 비교는 하지 않는다.', null, 'docs/DEMO_PLAN.md', null, false),
  ('demo-good-night', 20, '2026-06-21', null, 'good night 데모', 'demo', '60분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', 'good night', 'tracks/10_good-night/README.md', 'lyrics/10_good_night.txt', true),
  ('demo-good-night-arrangement-sketch', 30, '2026-06-22', null, 'good night 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '추가 악기 후보 1~2개와 다음 실험 조합 1개', '기타+보컬 데모를 바로 다시 들으며 어떤 악기가 붙어도 중심이 흐려지지 않는지 확인한다. 편곡 확정이 아니라 다음 실험 출발점만 남긴다.', 'good night', 'tracks/10_good-night/README.md', 'lyrics/10_good_night.txt', false),
  ('demo-psyche', 40, '2026-06-25', null, 'Psyche 데모', 'demo', '60~90분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', 'Psyche', 'tracks/01_psyche/README.md', 'lyrics/01_Psyche.txt', false),
  ('demo-psyche-arrangement-sketch', 50, '2026-06-26', null, 'Psyche 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '추가 악기 후보 2개와 첫 조합 메모', '기타+보컬 데모를 들으며 곡의 중심을 해치지 않는 추가 악기 후보를 적는다. 가장 먼저 시험할 조합 하나만 남긴다.', 'Psyche', 'tracks/01_psyche/README.md', 'lyrics/01_Psyche.txt', false),
  ('demo-gwaenhan-mal', 60, '2026-06-28', null, '괜한 말 데모', 'demo', '60분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '괜한 말', 'tracks/02_gwaenhan-mal/README.md', 'lyrics/02_괜한_말.txt', false),
  ('demo-gwaenhan-mal-arrangement-sketch', 70, '2026-06-29', null, '괜한 말 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '추가 악기 후보 2개와 첫 조합 메모', '데모를 바로 들으며 악기 수를 늘릴지, 질감만 보탤지 판단해본다. 다음 편곡 실험에 바로 옮길 조합 하나를 남긴다.', '괜한 말', 'tracks/02_gwaenhan-mal/README.md', 'lyrics/02_괜한_말.txt', false),
  ('demo-look-at-me', 80, '2026-07-01', null, '날 좀 봐줘요, 좀 봐줘요 데모', 'demo', '60분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '날 좀 봐줘요, 좀 봐줘요', 'tracks/03_look-at-me/README.md', 'lyrics/03_날_좀_봐줘요_좀_봐줘요.txt', false),
  ('demo-look-at-me-arrangement-sketch', 90, '2026-07-02', null, '날 좀 봐줘요, 좀 봐줘요 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '후렴 질감 메모와 첫 악기 조합 1개', '후렴의 에너지를 유지하면서 어떤 질감이 더 붙을 수 있는지 짧게 정리한다. 보컬과 통기타의 중심은 건드리지 않는다.', '날 좀 봐줘요, 좀 봐줘요', 'tracks/03_look-at-me/README.md', 'lyrics/03_날_좀_봐줘요_좀_봐줘요.txt', false),
  ('demo-nugungaui', 100, '2026-07-03', null, '누군가의 데모', 'demo', '60~90분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '누군가의', 'tracks/04_nugungaui/README.md', 'lyrics/04_누군가의.txt', false),
  ('demo-daedongje', 110, '2026-07-05', null, '대동제 데모', 'demo', '60~90분', '리듬 강세 정리, 보컬/기타 재녹음, 후반 일렉 솔로 테스트 메모', '드럼과 베이스의 박자, 강세를 먼저 정리하고 보컬과 기타를 다시 녹음한다. 데모 후반에는 뒷부분 일렉 솔로가 어울리는지도 가볍게 시험한다.', '대동제', 'tracks/05_daedongje/README.md', 'lyrics/05_대동제.txt', false),
  ('demo-ttodasi', 120, '2026-07-09', null, '또다시 데모', 'demo', '60분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '또다시', 'tracks/06_ttodasi/README.md', 'lyrics/06_또다시.txt', false),
  ('demo-nugungaui-arrangement-sketch', 130, '2026-07-04', null, '누군가의 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '추가 악기 후보 2~3개와 첫 조합 1개', '기타+보컬 데모를 다시 들으며 다른 악기 구성을 상상해본다. 편곡 확정이 아니라 다음 편곡 실험에서 가장 먼저 만져볼 조합 하나를 남기는 데 집중한다.', '누군가의', 'tracks/04_nugungaui/README.md', 'lyrics/04_누군가의.txt', false),
  ('demo-daedongje-arrangement-sketch', 140, '2026-07-06', null, '대동제 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '드럼/베이스 강세 기반 추가 악기 조합 1안', '이미 잡힌 리듬 강세를 기준으로 어떤 악기를 더하면 힘이 살아나는지 짧게 비교한다. 후반 일렉 솔로는 유지하되, 다른 악기와 겹치지 않는 한 가지 조합만 남긴다.', '대동제', 'tracks/05_daedongje/README.md', 'lyrics/05_대동제.txt', false),
  ('demo-ttodasi-arrangement-sketch', 150, '2026-07-10', null, '또다시 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '제출용 톤을 해치지 않는 추가 악기 조합 1안', '공모전 제출용 데모의 중심을 해치지 않는 범위에서만 다른 악기를 상상해본다. 보컬과 통기타를 흐리지 않는 조합 하나를 정리해 다음 편곡 출발점으로 남긴다.', '또다시', 'tracks/06_ttodasi/README.md', 'lyrics/06_또다시.txt', false),
  ('demo-2am', 160, '2026-07-12', null, '새벽 두 시 데모', 'demo', '60~90분', '전체 1테이크, 대체 가사 판단과 질감 스케치 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '새벽 두 시', 'tracks/07_2am/README.md', 'lyrics/07_새벽_두_시.txt', false),
  ('demo-2am-arrangement-sketch', 170, '2026-07-13', null, '새벽 두 시 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '대체 질감 메모와 첫 악기 조합 1개', '데모에서 느껴진 빈 공간을 기준으로 어떤 질감이 어울리는지 정리한다. 다음 편곡 실험에서 바로 비교할 조합 하나를 남긴다.', '새벽 두 시', 'tracks/07_2am/README.md', 'lyrics/07_새벽_두_시.txt', false),
  ('demo-noisy-night', 180, '2026-07-16', null, '소란스러운 밤 데모', 'demo', '60~90분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '소란스러운 밤', 'tracks/08_noisy-night/README.md', 'lyrics/08_소란스러운_밤.txt', false),
  ('demo-noisy-night-arrangement-sketch', 190, '2026-07-17', null, '소란스러운 밤 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '추가 악기 스케치와 첫 조합 1개', '기타+보컬 데모를 들으며 곡의 소란스러움을 키울지, 반대로 여백을 살릴지 가닥을 잡아본다. 다음 실험 조합 하나만 정리한다.', '소란스러운 밤', 'tracks/08_noisy-night/README.md', 'lyrics/08_소란스러운_밤.txt', false),
  ('demo-twenty-eight', 200, '2026-07-19', null, '스물 여덟 데모', 'demo', '60분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '스물 여덟', 'tracks/09_twenty-eight/README.md', 'lyrics/09_스물_여덟.txt', true),
  ('demo-twenty-eight-arrangement-sketch', 210, '2026-07-20', null, '스물 여덟 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '다음 편곡 출발 악기 조합 메모', '데모를 다시 들으며 곡의 온도를 유지하는 악기 조합을 상상해본다. 가장 먼저 손댈 조합 하나만 남긴다.', '스물 여덟', 'tracks/09_twenty-eight/README.md', 'lyrics/09_스물_여덟.txt', false),
  ('demo-budutga', 220, '2026-07-20', null, '부둣가 데모', 'demo', '60~90분', '전체 1테이크, 임시 키/BPM, 편곡 아이디어 메모', '통기타+보컬 전체 파일을 중심으로 남기되, 필요하면 짧은 악기 오버더빙이나 편곡 스케치를 함께 테스트한다. 연주 완성도보다 키, BPM, 구조와 다음 편곡 방향을 판단할 수 있는지가 중요하다.', '부둣가', 'tracks/11_budutga/README.md', 'lyrics/11_부둣가.txt', false),
  ('demo-budutga-arrangement-sketch', 230, '2026-07-21', null, '부둣가 데모 리뷰 + 악기 아이디어 정리', 'demo', '30분', '후렴 기준 악기 조합 메모', '데모를 다시 들으며 후렴의 중심을 기준으로 어떤 악기가 자연스럽게 들어올 수 있는지 정리한다. 다음 편곡 실험의 첫 조합 하나를 남긴다.', '부둣가', 'tracks/11_budutga/README.md', 'lyrics/11_부둣가.txt', false),
  ('demo-buffer', 240, '2026-07-21', null, '전곡 데모 보충 및 마감', 'demo', '최대 2시간', '후보 11곡 모두 판단 가능한 파일 보유', '누락 파일과 판단이 불가능한 테이크만 보충한다. 새 아이디어나 음색 탐색은 다음 단계로 넘긴다.', null, 'docs/DEMO_PLAN.md', null, true),
  ('structure-listen', 250, '2026-07-22', '2026-07-24', '11곡 연속 청취와 비교', 'structure', '2회 × 90분', '각 곡의 키, 템포, 구조 문제 목록', '녹음 직후의 감각이 아닌 앨범 전체 흐름으로 판단한다. 곡마다 바꿀 것 한 가지와 유지할 것 한 가지를 적는다.', null, 'docs/DEMO_PLAN.md', null, false),
  ('structure-retest', 260, '2026-07-25', '2026-07-28', '키·BPM 재테스트', 'structure', '최대 4곡', '판단이 어려운 곡의 후보 키/BPM 비교 파일', '모든 곡을 다시 녹음하지 않는다. 최고음, 최저음 또는 그루브가 불분명한 최대 네 곡만 짧게 비교한다.', null, 'docs/DEMO_PLAN.md', null, false),
  ('structure-lock', 270, '2026-07-29', '2026-07-31', '키·BPM·구조 확정', 'structure', '3시간', '최종 후보 8~9곡과 곡별 기본 정보 확정', '편곡 테스트가 시작된 뒤 반복해서 되돌아가지 않도록 곡의 뼈대를 결정 기록에 남긴다.', null, 'docs/DECISIONS.md', null, true),
  ('post-demo-direction', 280, '2026-07-29', '2026-08-01', '데모 이후 방향 논의', 'structure', '2회 × 60분', '최종 후보, 곡별 편곡 출발점, 모니터 스피커 준비 계획', '데모에서 간단한 편곡까지 한번 얹어본 상태를 기준으로, 어떤 곡을 밀고 어떤 곡을 줄일지 정리한다. 이때 편곡 시작 전 필요한 모니터 스피커 구매와 배치 일정도 함께 잠근다.', null, 'docs/POST_DEMO_DIRECTION.md', null, false),
  ('arrangement-monitoring', 290, '2026-08-01', '2026-08-03', '모니터 스피커 구매·배치', 'arrangement', '최대 3일', '편곡 판단용 모니터링 환경 준비', '데모 단계와 달리 편곡 판단은 스피커 기준으로 진행한다. 구매, 배치, 기준 청취까지 끝내고 나서 곡별 편곡 실험에 들어간다.', null, 'docs/POST_DEMO_DIRECTION.md', null, false),
  ('arrangement-palette', 300, '2026-08-03', '2026-08-04', '앨범 사운드 팔레트 설정', 'arrangement', '2시간', '통기타·보컬의 공통 질감과 추가 악기 원칙', '모니터 스피커 셋업 이후, 곡마다 별개의 세계를 만들기 전에 앨범 전체에 반복될 공간감, 악기 수와 보컬 거리감을 정한다.', null, 'docs/ALBUM.md', null, false),
  ('arrangement-week-1', 310, '2026-08-05', '2026-08-10', '편곡 테스트 1주차', 'arrangement', '3곡', '3곡의 편곡안 A/B와 선택 메모', '중요도가 높은 곡 세 곡부터 추가 악기, 리듬과 공간감의 두 가지 안을 빠르게 비교한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('arrangement-week-2', 320, '2026-08-11', '2026-08-16', '편곡 테스트 2주차', 'arrangement', '3곡', '다음 3곡의 편곡 방향 확정', '첫 주에 정한 앨범 팔레트를 적용하되 곡별 역할이 겹치지 않는지 확인한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('arrangement-week-3', 330, '2026-08-17', '2026-08-22', '편곡 테스트 3주차', 'arrangement', '남은 2~3곡', '전곡 편곡 방향과 본녹음 순서', '남은 곡을 정리하고 본녹음에 필요한 악기, 연주자와 세션 순서를 확정한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('arrangement-lock', 340, '2026-08-23', null, '전곡 편곡 방향 마감', 'arrangement', '마감', '본녹음에 들어갈 최종 편곡안', '이후에는 연주의 완성도와 소리의 품질에 집중한다. 새로운 편곡 방향은 추가하지 않는다.', null, 'docs/DECISIONS.md', null, true),
  ('recording-batch-a', 350, '2026-08-24', '2026-08-30', '본녹음 묶음 A', 'recording', '2곡', '최종 통기타·메인 보컬 2곡', '편곡 확신이 가장 높은 두 곡부터 최종 통기타와 메인 보컬을 녹음한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('recording-batch-b', 360, '2026-08-31', '2026-09-06', '본녹음 묶음 B', 'recording', '2곡', '최종 통기타·메인 보컬 누적 4곡', '메인 테이크를 우선 확정하고 더블링과 코러스는 별도 세션으로 분리한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('recording-batch-c', 370, '2026-09-07', '2026-09-13', '본녹음 묶음 C', 'recording', '2곡 + 크레딧 초안', '최종 녹음 누적 6곡, 참여자 크레딧 목록', '두 곡을 녹음하면서 지금까지 참여한 연주자, 엔지니어와 사용 악기를 함께 기록한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('recording-batch-d', 380, '2026-09-14', '2026-09-19', '본녹음 묶음 D', 'recording', '남은 2~3곡', '전곡 최종 통기타·메인 보컬', '남은 곡과 필수 코러스, 더블링을 마친다. 선택적 장식 파트는 우선순위를 낮춘다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('recording-lock', 390, '2026-09-20', null, '본녹음 핵심 마감', 'recording', '마감', '전곡 최종 통기타·메인 보컬 확보', '이 날짜 이후 본녹음은 누락과 명백한 문제를 해결하는 보충 녹음으로만 제한한다.', null, 'docs/SCHEDULE.md', null, true),
  ('post-edit-week', 400, '2026-09-21', '2026-09-27', '보충 녹음·컴핑·편집', 'post', '1주', '베스트 테이크, 튠과 타이밍 정리', '재녹음 목록을 먼저 닫고 컴핑, 호흡, 노이즈와 타이밍을 정리한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('post-recording-close', 410, '2026-09-28', '2026-09-30', '녹음 완전 마감·믹스 준비', 'post', '3일', '정리된 세션, 트랙명, 믹스 전달 파일', '사용하지 않는 트랙을 숨기고 파일명, 시작점, 샘플레이트와 레퍼런스 바운스를 확인한다.', null, 'docs/SCHEDULE.md', null, true),
  ('post-mix-prep', 420, '2026-10-01', '2026-10-04', '믹스 기준 설정', 'post', '4일', '기준곡 1곡과 앨범 믹스 원칙', '보컬의 전면감, 통기타 크기와 저역 기준을 한 곡에서 먼저 확정한다.', null, 'docs/SCHEDULE.md', null, false),
  ('post-mix-a', 430, '2026-10-05', '2026-10-11', '1차 믹스 전반부', 'post', '4곡', '전반부 곡 1차 믹스', '개별 곡의 화려함보다 기준곡과의 보컬·통기타 크기 일관성을 확인한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('post-mix-b', 440, '2026-10-12', '2026-10-18', '1차 믹스 후반부', 'post', '남은 4~5곡', '전곡 1차 믹스와 연속 청취본', '전곡을 순서대로 들으며 음량, 공간감과 곡 사이의 전환을 기록한다.', null, 'docs/TRACK_STATUS.md', null, false),
  ('post-mix-revision-1', 450, '2026-10-19', '2026-10-25', '믹스 수정 1차·가사/크레딧 교정', 'post', '1주', '수정 믹스와 확정 가사·크레딧', '믹스 수정은 곡마다 핵심 세 가지 이내로 제한한다. 동시에 제출용 가사와 크레딧을 교정한다.', null, 'docs/ALBUM.md', null, false),
  ('post-mix-final', 460, '2026-10-26', '2026-10-30', '최종 믹스 마감', 'post', '5일', '마스터링용 전곡 최종 믹스', '음악적 아이디어 추가를 중단하고 클릭, 노이즈, 출력 형식과 곡 시작·끝을 검수한다.', null, 'docs/SCHEDULE.md', null, true),
  ('post-master', 470, '2026-10-31', '2026-11-06', '마스터링·트랙 순서 확정', 'post', '1주', '전곡 마스터와 최종 트랙 순서', '다양한 재생 환경에서 확인하고 트랙 간 음량, 질감과 여백을 확정한다.', null, 'docs/SCHEDULE.md', null, true),
  ('delivery-package', 480, '2026-11-07', '2026-11-09', '유통 제출 패키지 조립', 'delivery', '3일', '마스터, 커버, 가사, 크레딧, 메타데이터', '곡 제목 표기, 참여자 이름, 작사·작곡·편곡 정보와 파일명을 하나의 제출본으로 모은다.', null, 'docs/ALBUM.md', null, false),
  ('delivery-qa', 490, '2026-11-10', '2026-11-12', '제출 전 최종 검수', 'delivery', '3일', '오탈자와 파일 오류가 없는 최종 패키지', '처음부터 다시 입력하지 말고 체크리스트에 따라 파일과 메타데이터를 대조한다.', null, 'docs/SCHEDULE.md', null, false),
  ('delivery-submit', 500, '2026-11-13', null, '유통사 전달', 'delivery', '고정 마감', '앨범 발매 자료 제출 완료', '12월 4일 발매를 위해 움직일 수 없는 최종 제출일이다.', null, 'docs/SCHEDULE.md', null, true),
  ('release-distribution-check', 510, '2026-11-16', '2026-11-22', '유통 반영 확인·발매 콘텐츠 준비', 'release', '1주', '플랫폼 정보 확인과 발매 공지 자료', '유통사에서 전달되는 미리보기와 표기를 확인하고 발매 공지에 필요한 이미지와 문구를 확정한다.', null, 'docs/SCHEDULE.md', null, false),
  ('release-promo-week', 520, '2026-11-23', '2026-11-29', '발매 전 공개 일정 실행', 'release', '1주', '티저와 발매 안내 공개', '준비된 콘텐츠를 일정대로 공개하고 음악 파일 자체는 다시 수정하지 않는다.', null, 'docs/SCHEDULE.md', null, false),
  ('release-final-week', 530, '2026-11-30', '2026-12-03', '발매 주 최종 확인', 'release', '4일', '링크, 소개문, 크레딧과 당일 게시물 준비', '발매 당일 필요한 링크와 게시물을 준비하고 휴식 시간을 확보한다.', null, 'docs/SCHEDULE.md', null, false),
  ('release-day', 540, '2026-12-04', null, '정규 앨범 발매', 'release', '발매일', '앨범 공개와 플랫폼 재생 확인', '플랫폼별 앨범 표기와 재생 상태를 확인하고 발매 공지를 게시한다.', null, 'docs/ALBUM.md', null, true);

insert into public.album_tracks (
  number, sort_order, title, due, event_id, document, lyrics
)
values
  ('01', 10, 'Psyche', '2026-06-25', 'demo-psyche', 'tracks/01_psyche/README.md', 'lyrics/01_Psyche.txt'),
  ('02', 20, '괜한 말', '2026-06-28', 'demo-gwaenhan-mal', 'tracks/02_gwaenhan-mal/README.md', 'lyrics/02_괜한_말.txt'),
  ('03', 30, '날 좀 봐줘요, 좀 봐줘요', '2026-07-01', 'demo-look-at-me', 'tracks/03_look-at-me/README.md', 'lyrics/03_날_좀_봐줘요_좀_봐줘요.txt'),
  ('04', 40, '누군가의', '2026-07-03', 'demo-nugungaui', 'tracks/04_nugungaui/README.md', 'lyrics/04_누군가의.txt'),
  ('05', 50, '대동제', '2026-07-05', 'demo-daedongje', 'tracks/05_daedongje/README.md', 'lyrics/05_대동제.txt'),
  ('06', 60, '또다시', '2026-07-09', 'demo-ttodasi', 'tracks/06_ttodasi/README.md', 'lyrics/06_또다시.txt'),
  ('07', 70, '새벽 두 시', '2026-07-12', 'demo-2am', 'tracks/07_2am/README.md', 'lyrics/07_새벽_두_시.txt'),
  ('08', 80, '소란스러운 밤', '2026-07-16', 'demo-noisy-night', 'tracks/08_noisy-night/README.md', 'lyrics/08_소란스러운_밤.txt'),
  ('09', 90, '스물 여덟', '2026-07-19', 'demo-twenty-eight', 'tracks/09_twenty-eight/README.md', 'lyrics/09_스물_여덟.txt'),
  ('10', 100, 'good night', '2026-06-21', 'demo-good-night', 'tracks/10_good-night/README.md', 'lyrics/10_good_night.txt'),
  ('11', 110, '부둣가', '2026-07-20', 'demo-budutga', 'tracks/11_budutga/README.md', 'lyrics/11_부둣가.txt');
